### ISSUE TITLE
chore: 6.x stable checklist

### ISSUE THREAD

**Issue by coryrylan** [vmware-clarity/core#45]
6.0 stable checklist

- [x] mark component beta/stable tags
- [ ] cut beta/stable for preparation for angular 14 release https://github.com/vmware-clarity/ng-clarity/issues/95 
- [ ] enable shim by default for `@clr/angular` see https://github.com/vmware-clarity/ng-clarity/issues/95 
- [ ] ensure storybook deployment applies to https://clarity.design/storybook/core
- [ ] after deployment mark the v4 `@clr/core`, `@clr/react` and `@clr/angular` packages as deprecated in npm

**Comment by astorije** [comment]
Adding a few elements here, in case it's helpful for a comprehensive upgrade guide:

- v6's deprecated `CdsInlineButton` doesn't work right on its own as the styling is incorrect. This gets resolved if a single `CdsButtonInline` gets imported in the project. We resolved this by renaming our `CdsInlineButton` into `CdsButtonInline` (which could use a mention in the upgrade guide)

- This same `CdsInlineButton` does not render its `role` correctly. Same resolution as above.

- We use an ℹ️ icon as input action, and it is now misaligned: <img width="85" alt="Screen Shot 2022-05-25 at 2 12 08 PM" src="https://user-images.githubusercontent.com/90871916/170259064-e061897b-60e8-4cb6-bfc1-c36226559a9a.png"> (v6) vs. <img width="87" alt="Screen Shot 2022-05-25 at 2 12 25 PM" src="https://user-images.githubusercontent.com/90871916/170259114-5eae8c72-ddd7-49d2-8a8d-f01ce1d1e09c.png"> (v5)
  See #87 for more context

- Internal components have been renamed so you might want to mention that in an upgrade guide. I realize they're supposed to be internal, but I opened a discussion about it since one of them were introduced for us (therefore not internal): https://github.com/vmware-clarity/core/discussions/94

- Upgrade guide should mention the CSS shims in Core must be removed.
